# Generated by Django 3.1 on 2021-05-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210527_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_telephone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone'),
        ),
    ]
