# Generated by Django 3.1 on 2021-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210527_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['branch_name']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_name']},
        ),
        migrations.AlterModelOptions(
            name='datacenter',
            options={'ordering': ['datacenter_name']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_name']},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['function_name']},
        ),
        migrations.AlterModelOptions(
            name='incident_detail',
            options={'ordering': ['-task_start']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['enq_id']},
        ),
        migrations.AlterModelOptions(
            name='serviceteam',
            options={'ordering': ['service_team_name']},
        ),
        migrations.AddField(
            model_name='customer',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='product',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.ManyToManyField(blank=True, null=True, to='app.Manager', verbose_name='Site-Manager'),
        ),
        migrations.AlterField(
            model_name='incident_detail',
            name='reference_product_caseNo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Reference Case-No'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_po',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer PO'),
        ),
    ]
