# Generated by Django 3.1 on 2021-07-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210610_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(max_length=100, verbose_name='Serial No'),
        ),
        migrations.AlterField(
            model_name='serviceteam',
            name='service_team_name',
            field=models.CharField(max_length=255, verbose_name='Service Team Name '),
        ),
    ]
