# Generated by Django 3.1 on 2021-09-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210727_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_close_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Incident-Closed-Date'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_customer_support',
            field=models.CharField(max_length=300, verbose_name='Customer Reference(Name | Tel)'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_description',
            field=models.TextField(verbose_name='Problem Description'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_problem_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Complete Date/Time'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_problem_start',
            field=models.DateTimeField(verbose_name='Response Date/Time'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_reference_customer_caseNo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Reference Case No.'),
        ),
        migrations.AlterField(
            model_name='incident_detail',
            name='task_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Task End Date'),
        ),
        migrations.AlterField(
            model_name='incident_detail',
            name='task_start',
            field=models.DateTimeField(verbose_name='Task Start Date'),
        ),
    ]
