# Generated by Django 3.1 on 2021-09-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210913_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type_name', models.CharField(max_length=50, verbose_name='Incident Type')),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_close_datetime',
            field=models.DateTimeField(blank=True, help_text='For closed status', null=True, verbose_name='Incident-Closed-Date'),
        ),
    ]
