# Generated by Django 3.1 on 2021-09-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210915_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident_type',
            name='incident_type_name',
            field=models.CharField(max_length=150, verbose_name='Incident Type'),
        ),
    ]
