# Generated by Django 3.1 on 2021-09-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210915_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_customer_support',
            field=models.CharField(max_length=300, verbose_name='Customer Reference(Name,Tel)'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_reference_customer_caseNo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Customer Reference Case No.'),
        ),
    ]
