# Generated by Django 3.1 on 2021-11-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210915_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type_name', models.CharField(max_length=150, verbose_name='Service Type')),
            ],
        ),
    ]
