# Generated by Django 3.1 on 2021-11-12 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.service_type', verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.incident_type', verbose_name='Incident Type'),
        ),
    ]
