# Generated by Django 3.1 on 2022-01-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211112_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='storage_capacity',
            field=models.FloatField(default=0.0, help_text='If product type is storage,fill in this field', verbose_name='Storage Size(TB)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_subcontractor',
            field=models.BooleanField(default=False, verbose_name='Is Sub Contractor'),
        ),
    ]
