# Generated by Django 3.1 on 2022-01-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220120_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='storage_capacity',
            field=models.FloatField(blank=True, help_text='If product type is storage,fill in this field', null=True, verbose_name='Storage Size(TB)'),
        ),
    ]
