# Generated by Django 3.1 on 2022-01-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220120_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='storage_capacity',
            field=models.FloatField(default=0, help_text='If product type is storage,fill in this field', verbose_name='Storage Size(TB)'),
        ),
    ]
