# Generated by Django 3.1 on 2022-03-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220120_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_site_manager',
            field=models.BooleanField(default=True, verbose_name='Is SiteManager'),
        ),
    ]
