# Generated by Django 3.1 on 2022-03-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_manager_is_site_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_subject',
            field=models.CharField(default='-', max_length=255, verbose_name='Problem Subject'),
        ),
    ]
