# Generated by Django 3.1 on 2022-03-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_incident_incident_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_subject',
            field=models.CharField(max_length=255, verbose_name='Problem Subject'),
        ),
    ]
