# Generated by Django 3.1 on 2022-04-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220325_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-incident_datetime']},
        ),
        migrations.AddField(
            model_name='project',
            name='project_end',
            field=models.DateField(default='2022-12-31', verbose_name='Project-End'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_start',
            field=models.DateField(default='2022-01-01', verbose_name='Project-Start'),
        ),
    ]
