# Generated by Django 3.1 on 2022-06-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220425_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportKeyValueWeight',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Key')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('weight_value', models.FloatField(help_text='0-100', verbose_name='Weight Value')),
                ('is_used', models.BooleanField(default=True, verbose_name='Is Used')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('level1', models.FloatField(help_text='>= value', verbose_name='Level 1')),
                ('level2', models.FloatField(help_text='>= value', verbose_name='Level 2')),
                ('level3', models.FloatField(help_text='>= value', verbose_name='Level 3')),
                ('level4', models.FloatField(help_text='>= value', verbose_name='Level 4')),
                ('level5', models.FloatField(help_text='>= value', verbose_name='Level 5')),
            ],
            options={
                'db_table': 'report_key_value_weight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportLevelDefinition',
            fields=[
                ('key', models.CharField(help_text='it must be exactly identical to the column name in report_key_value_weight table.', max_length=20, primary_key=True, serialize=False, verbose_name='Key')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('level_value', models.IntegerField(help_text='1,2,3 ... in sequence', unique=True, verbose_name='Value')),
            ],
            options={
                'db_table': 'report_level_definition',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='failure_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Failure Type'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_problem_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolved Date/Time'),
        ),
    ]
