# Generated by Django 3.2.16 on 2022-12-20 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0023_auto_20220621_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM_Inventory_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file_name', models.CharField(max_length=100, unique=True, verbose_name='File Name')),
                ('template_des', models.CharField(blank=True, max_length=255, null=True, verbose_name='Des')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='required_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TaskSchedule_PMDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='Create Date')),
                ('complete_date', models.DateTimeField(blank=True, null=True, verbose_name='Complete Date')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
                ('pm_id', models.IntegerField(verbose_name='PM ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name')),
                ('file_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='File Password')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='PreventiveMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='PM PlanedDate')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='PM Period')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='PM_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateField(verbose_name='ActualDate To PM')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='DocumentDate To PM')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remark')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('is_pm', models.BooleanField(default=True, verbose_name='Is PM')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Engineer')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inventory', verbose_name='Inventory')),
                ('pm_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.preventivemaintenance', verbose_name='PM Master')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='pm_inventory_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pm_inventory_template', verbose_name='PM Template '),
        ),
    ]
