# Generated by Django 3.2.16 on 2022-12-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20221220_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='planned_date',
            field=models.DateField(help_text='The first day of the month e.g. 1/12/2022', verbose_name='PM Plan(Month)'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='remark',
            field=models.CharField(blank=True, help_text=' e.g. 1/2 ,2/4', max_length=255, null=True, verbose_name='PM Period'),
        ),
    ]
