# Generated by Django 3.2.16 on 2022-12-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20221221_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='remark',
            field=models.CharField(help_text=' e.g. 1/2 ,2/4', max_length=255, verbose_name='PM Period'),
        ),
    ]
