# Generated by Django 3.2.16 on 2023-01-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20230109_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='firmware_bios_version',
            field=models.CharField(blank=True, help_text='Bios for Server,Firmware for Storage.', max_length=100, null=True, verbose_name='HW(Firmware/Bios) Version'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='firmware_bundle_version',
            field=models.CharField(blank=True, help_text='HPE=SPP,Dell=SUU,CISCO=HUU', max_length=100, null=True, verbose_name='Firmware Bundle Version'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='hw_management_version',
            field=models.CharField(blank=True, help_text='ILO Version,IDRAC Version.', max_length=100, null=True, verbose_name='HW Management Version'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='ip_address2',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address 2'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='ip_address3',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address 3'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='password2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Password 2'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='password3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Password 3'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sw_management_version',
            field=models.CharField(blank=True, help_text='OVC Version,VDI Version.', max_length=100, null=True, verbose_name='SW Management Version'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='username2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Username 2'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='username3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Username 3'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='device_hs_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Device(HW/OS/SW) Version'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address Management'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Password Management'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='User Name Management'),
        ),
    ]
