# Generated by Django 3.2.16 on 2023-01-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20230112_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Team Lead'),
        ),
    ]
