# Generated by Django 3.2.16 on 2023-01-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_project_team_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_lead',
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Team Lead'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contract-NO'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(help_text='for no serial , -', max_length=100, verbose_name='Serial No'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_po',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cust-PO'),
        ),
    ]
