# Generated by Django 3.2.16 on 2023-01-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20230119_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm_inventory',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='ActualDate To PM'),
        ),
    ]
