# Generated by Django 3.2.16 on 2023-02-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_pm_inventory_actual_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_inactive',
            field=models.BooleanField(default=False, verbose_name='Is Not Active(ลาออก)'),
        ),
    ]
