# Generated by Django 3.2.16 on 2023-02-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_employee_is_inactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_company_name', models.CharField(max_length=255, unique=True, verbose_name='Sub Company Name')),
                ('sub_company_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sub Company Address')),
                ('head_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Head Company')),
            ],
            options={
                'ordering': ['sub_company_name'],
            },
        ),
    ]
