# Generated by Django 3.2.16 on 2023-02-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_preventivemaintenance_customer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='customer_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.subcompany', verbose_name='Customer Company'),
            preserve_default=False,
        ),
    ]
