# Generated by Django 3.2.16 on 2023-03-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_preventivemaintenance_customer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='contact_name',
            field=models.CharField(default='-', max_length=255, verbose_name='Contact Name'),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='contact_telephone',
            field=models.CharField(default='', max_length=50, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='equipment_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipment_Location'),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='site_branch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site/Branch'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contract-NO/Reference'),
        ),
    ]
