# Generated by Django 3.2.16 on 2023-03-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20230302_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='contact_name',
            field=models.CharField(default='', max_length=255, verbose_name='Contact Name'),
        ),
    ]
