# Generated by Django 3.2.16 on 2023-03-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_preventivemaintenance_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='equipment_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipment Location'),
        ),
    ]
