# Generated by Django 3.2.16 on 2023-03-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_preventivemaintenance_equipment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_managed_by_admin',
            field=models.BooleanField(default=False, verbose_name='Is Managed By Admin'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='part_detail',
            field=models.JSONField(blank=True, default={}, help_text='default value = {}', null=True, verbose_name='Part Detail'),
        ),
    ]
