# Generated by Django 3.2.16 on 2023-03-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20230315_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm_inventory_template',
            name='sample_part_detail',
            field=models.JSONField(blank=True, default={}, help_text='default value = {}', null=True, verbose_name='Sample JSON Format for Part Detail'),
        ),
    ]
