# Generated by Django 3.2.16 on 2023-04-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_pm_inventory_template_sample_part_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm_inventory_template',
            name='template_des',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Template Name'),
        ),
        migrations.CreateModel(
            name='Prediction_ML_Severity_Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_label', models.IntegerField(verbose_name='Severity Label Prediction')),
                ('severity_name', models.CharField(max_length=50, verbose_name='Severity Label Prediction')),
                ('prediction_at', models.DateTimeField(verbose_name='Prediction At')),
                ('imported_at', models.DateTimeField(verbose_name='Imported At')),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.incident', verbose_name='Incident ID')),
            ],
        ),
    ]
