# Generated by Django 3.2.16 on 2023-07-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20230615_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction_ml_severity_incident',
            name='model_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Model Version'),
        ),
        migrations.CreateModel(
            name='Prediction_ML2_everity_Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_label', models.IntegerField(verbose_name='Severity Label Prediction')),
                ('prediction_at', models.DateTimeField(verbose_name='Prediction At')),
                ('imported_at', models.DateTimeField(verbose_name='Imported At')),
                ('model_version', models.CharField(max_length=50, verbose_name='Model Version')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.incident', verbose_name='Incident ID')),
            ],
        ),
    ]
