# Generated by Django 3.2.16 on 2023-10-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_prediction_ml2_everity_incident_severity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Engineer Incident Owner'),
        ),
    ]
