# Generated by Django 3.2.16 on 2023-10-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_incident_incident_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Engineer Incident Owner'),
        ),
    ]
