# Generated by Django 3.2.16 on 2023-11-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_incident_incident_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='ended_pm_date',
            field=models.DateField(blank=True, help_text='The last day of the month e.g. 31/12/2022', null=True, verbose_name='End PM(Day)'),
        ),
    ]
