# Generated by Django 3.2.16 on 2023-11-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_preventivemaintenance_ended_pm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='ended_pm_date',
            field=models.DateField(help_text='The last day of the month e.g. 31/12/2022', verbose_name='End PM(Day)'),
        ),
    ]
