# Generated by Django 3.2.16 on 2023-11-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_preventivemaintenance_ended_pm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='team_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_engineer', to='app.employee', verbose_name='Team Lead'),
        ),
    ]
