# Generated by Django 3.2.23 on 2023-12-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_preventivemaintenance_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update At'),
        ),
    ]
