# Generated by Django 3.2.23 on 2023-12-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_preventivemaintenance_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='postponed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Postpone PM'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_pm',
            field=models.BooleanField(default=False, verbose_name='Has PM'),
        ),
        migrations.AddField(
            model_name='project',
            name='pm_des',
            field=models.CharField(blank=True, help_text='Describe detail(if it has PM)', max_length=255, null=True, verbose_name='PM Des'),
        ),
    ]
