# Generated by Django 3.2.23 on 2024-02-02 08:51

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20231213_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_close_datetime',
            field=models.DateTimeField(blank=True, help_text='For closed status', null=True, validators=[app.models.validate_datetime_field_1year], verbose_name='Incident-Closed-Date'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_datetime',
            field=models.DateTimeField(validators=[app.models.validate_datetime_field_1year], verbose_name='Incident-Date'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_problem_end',
            field=models.DateTimeField(blank=True, null=True, validators=[app.models.validate_datetime_field_1year], verbose_name='Resolved Date/Time'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_problem_start',
            field=models.DateTimeField(validators=[app.models.validate_datetime_field_1year], verbose_name='Response Date/Time'),
        ),
        migrations.AlterField(
            model_name='incident_detail',
            name='task_end',
            field=models.DateTimeField(blank=True, null=True, validators=[app.models.validate_datetime_field_1year], verbose_name='Task End Date'),
        ),
        migrations.AlterField(
            model_name='incident_detail',
            name='task_start',
            field=models.DateTimeField(validators=[app.models.validate_datetime_field_1year], verbose_name='Task Start Date'),
        ),
        migrations.AlterField(
            model_name='pm_inventory',
            name='actual_date',
            field=models.DateField(blank=True, null=True, validators=[app.models.validate_datetime_field_1year], verbose_name='ActualDate To PM'),
        ),
        migrations.AlterField(
            model_name='pm_inventory',
            name='document_date',
            field=models.DateField(blank=True, null=True, validators=[app.models.validate_datetime_field_1year], verbose_name='DocumentDate To PM'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='ended_pm_date',
            field=models.DateField(help_text='The last day of the month e.g. 31/12/2022', validators=[app.models.validate_datetime_field_1year], verbose_name='End PM(Day)'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='planned_date',
            field=models.DateField(help_text='The first day of the month e.g. 1/12/2022', validators=[app.models.validate_datetime_field_1year], verbose_name='PM Plan(Month)'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='postponed_date',
            field=models.DateField(blank=True, null=True, validators=[app.models.validate_datetime_field_1year], verbose_name='Postpone PM'),
        ),
        migrations.AlterField(
            model_name='serviceteam',
            name='company',
            field=models.ForeignKey(default=1, help_text='Default=Yip - Yip In Tsoi', on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Yip and SubContractor'),
        ),
        migrations.CreateModel(
            name='Incident_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_content', models.TextField(blank=True, null=True, verbose_name='Incident Content')),
                ('output_summary', models.TextField(verbose_name='Incident Summary')),
                ('model', models.CharField(max_length=50, verbose_name='GenAI-Model')),
                ('incident_updated_at', models.DateTimeField(validators=[app.models.validate_datetime_field_1year], verbose_name='Last Incident Update DateTime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.incident', verbose_name='Incident')),
            ],
        ),
    ]
