# Generated by Django 3.2.23 on 2024-02-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20240202_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident_summary',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.incident', unique=True, verbose_name='Incident'),
        ),
    ]
