# Generated by Django 3.2.23 on 2024-02-02 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0055_alter_incident_summary_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident_Summary_UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfactory', models.BooleanField(verbose_name='Satisfactory')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('incident_summary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.incident_summary')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
